/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.CrudPedido;
import Classes.Pedido;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author natan
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        ListarDesc(String.valueOf(LocalDate.now()), String.valueOf(LocalDate.now()));
    }

    public void ListarDesc(String desc, String desc2) {
        CrudPedido lista = new CrudPedido();
        double vt = 0;
        for (Pedido l : lista.mostrar(desc, desc2)) {
            vt += l.getValor();
            lblUltima.setText("Ultimo venda: R$" + l.getValor() + "0");
        }
        lblDia.setText("Saldo do Dia:R$" + vt + "0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRelatorio = new javax.swing.JPanel();
        btnRelatorioPeriodo = new javax.swing.JButton();
        btnRelatorioVenda = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDia = new javax.swing.JLabel();
        lblUltima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelRelatorio.setBackground(new java.awt.Color(255, 102, 0));

        btnRelatorioPeriodo.setBackground(new java.awt.Color(51, 102, 255));
        btnRelatorioPeriodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRelatorioPeriodo.setText("Relatório por Período");
        btnRelatorioPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioPeriodoMouseClicked(evt);
            }
        });
        btnRelatorioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPeriodoActionPerformed(evt);
            }
        });

        btnRelatorioVenda.setBackground(new java.awt.Color(51, 102, 255));
        btnRelatorioVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRelatorioVenda.setText("Relatório por Venda");
        btnRelatorioVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioVendaMouseClicked(evt);
            }
        });
        btnRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioVendaActionPerformed(evt);
            }
        });

        btnRetornar.setBackground(new java.awt.Color(255, 102, 0));
        btnRetornar.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Retornar.png"))); // NOI18N
        btnRetornar.setText("     Retornar");
        btnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetornarMouseClicked(evt);
            }
        });
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        lblDia.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(255, 255, 255));
        lblDia.setText("Saldo do Dia:R$56,00");

        lblUltima.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblUltima.setForeground(new java.awt.Color(255, 255, 255));
        lblUltima.setText("Ultimo venda: R$12,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUltima)
                .addGap(76, 76, 76)
                .addComponent(lblDia)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltima)
                    .addComponent(lblDia))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelRelatorioLayout = new javax.swing.GroupLayout(PainelRelatorio);
        PainelRelatorio.setLayout(PainelRelatorioLayout);
        PainelRelatorioLayout.setHorizontalGroup(
            PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(btnRelatorioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(btnRelatorioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelRelatorioLayout.setVerticalGroup(
            PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addGroup(PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPeriodoActionPerformed
        frmRelatorioPeriodo tela = new frmRelatorioPeriodo();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRelatorioPeriodoActionPerformed

    private void btnRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioVendaActionPerformed
        frmRelatorioVenda tela = new frmRelatorioVenda();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRelatorioVendaActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed

    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarMouseClicked
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetornarMouseClicked

    private void btnRelatorioPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioPeriodoMouseClicked
        frmRelatorioPeriodo tela = new frmRelatorioPeriodo();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRelatorioPeriodoMouseClicked

    private void btnRelatorioVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioVendaMouseClicked
        frmRelatorioVenda tela = new frmRelatorioVenda();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRelatorioVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRelatorio;
    private javax.swing.JButton btnRelatorioPeriodo;
    private javax.swing.JButton btnRelatorioVenda;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblUltima;
    // End of variables declaration//GEN-END:variables
}
