/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author Bruno Sousa
 */
public class TelaDeCardapio extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCardapio
     */
    public TelaDeCardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpItem1 = new javax.swing.JPanel();
        lblItem1 = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        lblDescricao1 = new javax.swing.JLabel();
        btnAddPedido1 = new javax.swing.JButton();
        jpItem3 = new javax.swing.JPanel();
        lblItem3 = new javax.swing.JLabel();
        lblPreco3 = new javax.swing.JLabel();
        lblDescricao3 = new javax.swing.JLabel();
        btnAddPedido3 = new javax.swing.JButton();
        jpItem2 = new javax.swing.JPanel();
        lblItem2 = new javax.swing.JLabel();
        lblPreco2 = new javax.swing.JLabel();
        lblDescricao2 = new javax.swing.JLabel();
        btnAddPedido2 = new javax.swing.JButton();
        jpCardapio = new javax.swing.JPanel();
        lblCategoria5 = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        lblCategoria3 = new javax.swing.JLabel();
        lblCategoria2 = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        lblCardapio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jpItem1.setBackground(new java.awt.Color(51, 51, 51));
        jpItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpItem1.setForeground(new java.awt.Color(102, 102, 102));

        lblItem1.setBackground(new java.awt.Color(255, 255, 255));
        lblItem1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItem1.setForeground(new java.awt.Color(255, 255, 255));
        lblItem1.setText("Item1");

        lblPreco1.setBackground(new java.awt.Color(255, 255, 255));
        lblPreco1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPreco1.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco1.setText("preço1");

        lblDescricao1.setBackground(new java.awt.Color(255, 255, 255));
        lblDescricao1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDescricao1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao1.setText("descrição1");

        btnAddPedido1.setBackground(new java.awt.Color(255, 153, 0));
        btnAddPedido1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPedido1.setText("+ Adicionar ao Pedido");
        btnAddPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPedido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpItem1Layout = new javax.swing.GroupLayout(jpItem1);
        jpItem1.setLayout(jpItem1Layout);
        jpItem1Layout.setHorizontalGroup(
            jpItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem1Layout.createSequentialGroup()
                .addGroup(jpItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpItem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDescricao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpItem1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addGroup(jpItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpItem1Layout.createSequentialGroup()
                        .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(btnAddPedido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpItem1Layout.setVerticalGroup(
            jpItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpItem1Layout.createSequentialGroup()
                        .addComponent(lblPreco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(72, 72, 72)
                        .addComponent(btnAddPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpItem1Layout.createSequentialGroup()
                        .addComponent(lblItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jpItem3.setBackground(new java.awt.Color(51, 51, 51));
        jpItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpItem3.setForeground(new java.awt.Color(102, 102, 102));

        lblItem3.setBackground(new java.awt.Color(255, 255, 255));
        lblItem3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItem3.setForeground(new java.awt.Color(255, 255, 255));
        lblItem3.setText("Item3");

        lblPreco3.setBackground(new java.awt.Color(255, 255, 255));
        lblPreco3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPreco3.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco3.setText("preço3");

        lblDescricao3.setBackground(new java.awt.Color(255, 255, 255));
        lblDescricao3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDescricao3.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao3.setText("descrição3");

        btnAddPedido3.setBackground(new java.awt.Color(255, 153, 0));
        btnAddPedido3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPedido3.setText("+ Adicionar ao Pedido");

        javax.swing.GroupLayout jpItem3Layout = new javax.swing.GroupLayout(jpItem3);
        jpItem3.setLayout(jpItem3Layout);
        jpItem3Layout.setHorizontalGroup(
            jpItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem3Layout.createSequentialGroup()
                .addGroup(jpItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpItem3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDescricao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpItem3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addGroup(jpItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpItem3Layout.createSequentialGroup()
                        .addComponent(lblPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(btnAddPedido3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpItem3Layout.setVerticalGroup(
            jpItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpItem3Layout.createSequentialGroup()
                        .addComponent(lblItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpItem3Layout.createSequentialGroup()
                        .addComponent(lblPreco3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(btnAddPedido3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jpItem2.setBackground(new java.awt.Color(51, 51, 51));
        jpItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpItem2.setForeground(new java.awt.Color(102, 102, 102));

        lblItem2.setBackground(new java.awt.Color(255, 255, 255));
        lblItem2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItem2.setForeground(new java.awt.Color(255, 255, 255));
        lblItem2.setText("Item2");

        lblPreco2.setBackground(new java.awt.Color(255, 255, 255));
        lblPreco2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPreco2.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco2.setText("preço2");

        lblDescricao2.setBackground(new java.awt.Color(255, 255, 255));
        lblDescricao2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDescricao2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao2.setText("descrição2");

        btnAddPedido2.setBackground(new java.awt.Color(255, 153, 0));
        btnAddPedido2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPedido2.setText("+ Adicionar ao Pedido");

        javax.swing.GroupLayout jpItem2Layout = new javax.swing.GroupLayout(jpItem2);
        jpItem2.setLayout(jpItem2Layout);
        jpItem2Layout.setHorizontalGroup(
            jpItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem2Layout.createSequentialGroup()
                .addGroup(jpItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpItem2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDescricao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpItem2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addGroup(jpItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpItem2Layout.createSequentialGroup()
                        .addComponent(lblPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(btnAddPedido2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpItem2Layout.setVerticalGroup(
            jpItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpItem2Layout.createSequentialGroup()
                        .addComponent(lblItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpItem2Layout.createSequentialGroup()
                        .addComponent(lblPreco2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(btnAddPedido2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jpItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jpItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jpItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jpCardapio.setBackground(new java.awt.Color(51, 51, 51));

        lblCategoria5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCategoria5.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria5.setText("Categoria5");

        lblCategoria4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCategoria4.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria4.setText("Categoria4");

        lblCategoria3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCategoria3.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria3.setText("Categoria3");

        lblCategoria2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCategoria2.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setText("Categoria2");

        lblCategoria1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setText("Categoria1");

        lblCardapio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCardapio.setForeground(new java.awt.Color(255, 255, 255));
        lblCardapio.setText("Cardápio");

        javax.swing.GroupLayout jpCardapioLayout = new javax.swing.GroupLayout(jpCardapio);
        jpCardapio.setLayout(jpCardapioLayout);
        jpCardapioLayout.setHorizontalGroup(
            jpCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCardapioLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jpCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCardapioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpCardapioLayout.setVerticalGroup(
            jpCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardapioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jpCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPedido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPedido1;
    private javax.swing.JButton btnAddPedido2;
    private javax.swing.JButton btnAddPedido3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpCardapio;
    private javax.swing.JPanel jpItem1;
    private javax.swing.JPanel jpItem2;
    private javax.swing.JPanel jpItem3;
    private javax.swing.JLabel lblCardapio;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCategoria3;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria5;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblItem2;
    private javax.swing.JLabel lblItem3;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblPreco3;
    // End of variables declaration//GEN-END:variables
}
