/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Matheus
 */
public class TelaAddRemIngrediente extends javax.swing.JFrame {

    /**
     * Creates new form PersProduto
     */
    public TelaAddRemIngrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        lblIngrediente4 = new javax.swing.JLabel();
        lblIngrediente1 = new javax.swing.JLabel();
        lblIngrediente2 = new javax.swing.JLabel();
        lblIngrediente3 = new javax.swing.JLabel();
        lblIngrediente5 = new javax.swing.JLabel();
        lblIngrediente6 = new javax.swing.JLabel();
        lblIngrediente7 = new javax.swing.JLabel();
        lblIngrediente8 = new javax.swing.JLabel();
        lblIngrediente9 = new javax.swing.JLabel();
        lblIngrediente10 = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        lblPreco2 = new javax.swing.JLabel();
        lblPreco3 = new javax.swing.JLabel();
        lblPreco4 = new javax.swing.JLabel();
        lblPreco5 = new javax.swing.JLabel();
        lblPreco10 = new javax.swing.JLabel();
        lblPreco9 = new javax.swing.JLabel();
        lblPreco8 = new javax.swing.JLabel();
        lblPreco7 = new javax.swing.JLabel();
        lblPreco6 = new javax.swing.JLabel();
        btnRem1 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnAdd2 = new javax.swing.JButton();
        btnRem2 = new javax.swing.JButton();
        btnRem3 = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        btnAdd4 = new javax.swing.JButton();
        btnRem4 = new javax.swing.JButton();
        btnRem5 = new javax.swing.JButton();
        btnAdd5 = new javax.swing.JButton();
        btnAdd6 = new javax.swing.JButton();
        btnRem6 = new javax.swing.JButton();
        btnRem7 = new javax.swing.JButton();
        btnAdd7 = new javax.swing.JButton();
        btnRem8 = new javax.swing.JButton();
        btnAdd8 = new javax.swing.JButton();
        btnRem9 = new javax.swing.JButton();
        btnAdd9 = new javax.swing.JButton();
        btnRem10 = new javax.swing.JButton();
        btnAdd10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar ou remover itens");
        jLabel1.setToolTipText("");

        jButton5.setBackground(new java.awt.Color(255, 165, 24));
        jButton5.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton5.setText("Concluir");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lblIngrediente4.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente4.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente4.setText("Ingrediente4");

        lblIngrediente1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente1.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente1.setText("Ingrediente1");

        lblIngrediente2.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente2.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente2.setText("Ingrediente2");
        lblIngrediente2.setToolTipText("");

        lblIngrediente3.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente3.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente3.setText("Ingrediente3");

        lblIngrediente5.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente5.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente5.setText("Ingrediente5");

        lblIngrediente6.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente6.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente6.setText("Ingrediente6");

        lblIngrediente7.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente7.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente7.setText("Ingrediente7");
        lblIngrediente7.setToolTipText("");

        lblIngrediente8.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente8.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente8.setText("Ingrediente8");

        lblIngrediente9.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente9.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente9.setText("Ingrediente9");

        lblIngrediente10.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblIngrediente10.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngrediente10.setText("Ingrediente10");

        lblPreco1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco1.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco1.setText("Preço1");

        lblPreco2.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco2.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco2.setText("Preço2");

        lblPreco3.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco3.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco3.setText("Preço3");

        lblPreco4.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco4.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco4.setText("Preço4");

        lblPreco5.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco5.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco5.setText("Preço5");

        lblPreco10.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco10.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco10.setText("Preço10");

        lblPreco9.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco9.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco9.setText("Preço9");

        lblPreco8.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco8.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco8.setText("Preço8");

        lblPreco7.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco7.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco7.setText("Preço7");

        lblPreco6.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        lblPreco6.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco6.setText("Preço6");

        btnRem1.setBackground(new java.awt.Color(254, 92, 84));
        btnRem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem1.setText("-");

        btnAdd1.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd1.setText("+");

        btnAdd2.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd2.setText("+");

        btnRem2.setBackground(new java.awt.Color(254, 92, 84));
        btnRem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem2.setText("-");

        btnRem3.setBackground(new java.awt.Color(254, 92, 84));
        btnRem3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem3.setText("-");

        btnAdd3.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd3.setText("+");

        btnAdd4.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd4.setText("+");

        btnRem4.setBackground(new java.awt.Color(254, 92, 84));
        btnRem4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem4.setText("-");

        btnRem5.setBackground(new java.awt.Color(254, 92, 84));
        btnRem5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem5.setText("-");

        btnAdd5.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd5.setText("+");

        btnAdd6.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd6.setText("+");

        btnRem6.setBackground(new java.awt.Color(254, 92, 84));
        btnRem6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem6.setText("-");

        btnRem7.setBackground(new java.awt.Color(254, 92, 84));
        btnRem7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem7.setText("-");

        btnAdd7.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd7.setText("+");

        btnRem8.setBackground(new java.awt.Color(254, 92, 84));
        btnRem8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem8.setText("-");

        btnAdd8.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd8.setText("+");

        btnRem9.setBackground(new java.awt.Color(254, 92, 84));
        btnRem9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem9.setText("-");

        btnAdd9.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd9.setText("+");

        btnRem10.setBackground(new java.awt.Color(254, 92, 84));
        btnRem10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRem10.setText("-");

        btnAdd10.setBackground(new java.awt.Color(2, 248, 148));
        btnAdd10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd10.setText("+");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPreco4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblPreco3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRem1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRem2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRem3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRem4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRem5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngrediente10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPreco10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreco6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRem6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdd6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRem10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdd10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRem9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRem8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRem7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem1)
                            .addComponent(btnAdd1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem2)
                            .addComponent(btnAdd2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem3)
                            .addComponent(btnAdd3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem4)
                            .addComponent(btnAdd4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem5)
                            .addComponent(btnAdd5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblIngrediente6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblIngrediente7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblIngrediente8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblIngrediente9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblIngrediente10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPreco6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRem6)
                                .addComponent(btnAdd6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPreco7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRem7)
                                .addComponent(btnAdd7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPreco8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRem8)
                                .addComponent(btnAdd8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPreco9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRem9)
                                .addComponent(btnAdd9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPreco10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRem10)
                                .addComponent(btnAdd10))))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(33, 33, 33))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome do Produto");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descrição do Produto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       /* PersProdRem x = new PersProdRem ();
        x.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddRemIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddRemIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddRemIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddRemIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddRemIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd10;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAdd5;
    private javax.swing.JButton btnAdd6;
    private javax.swing.JButton btnAdd7;
    private javax.swing.JButton btnAdd8;
    private javax.swing.JButton btnAdd9;
    private javax.swing.JButton btnRem1;
    private javax.swing.JButton btnRem10;
    private javax.swing.JButton btnRem2;
    private javax.swing.JButton btnRem3;
    private javax.swing.JButton btnRem4;
    private javax.swing.JButton btnRem5;
    private javax.swing.JButton btnRem6;
    private javax.swing.JButton btnRem7;
    private javax.swing.JButton btnRem8;
    private javax.swing.JButton btnRem9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblIngrediente1;
    private javax.swing.JLabel lblIngrediente10;
    private javax.swing.JLabel lblIngrediente2;
    private javax.swing.JLabel lblIngrediente3;
    private javax.swing.JLabel lblIngrediente4;
    private javax.swing.JLabel lblIngrediente5;
    private javax.swing.JLabel lblIngrediente6;
    private javax.swing.JLabel lblIngrediente7;
    private javax.swing.JLabel lblIngrediente8;
    private javax.swing.JLabel lblIngrediente9;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblPreco10;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblPreco3;
    private javax.swing.JLabel lblPreco4;
    private javax.swing.JLabel lblPreco5;
    private javax.swing.JLabel lblPreco6;
    private javax.swing.JLabel lblPreco7;
    private javax.swing.JLabel lblPreco8;
    private javax.swing.JLabel lblPreco9;
    // End of variables declaration//GEN-END:variables
}
